import React from "react";
import { notFound } from "next/navigation";
import { Metadata } from "next";
import { searchManga } from "app/data/dataFetching";
import MangaScreen from "@/components/MangaScreen";

export async function generateMetadata({
    searchParams,
  }: {
    searchParams?: { [key: string]: string | string[] | undefined };
  }): Promise<Metadata> {
    const { sort, q: searchValue } = searchParams as { [key: string]: string };
    const data = await searchManga(searchValue);
  
    if (!data) return notFound();
  
    return {
      title: `MangaReader - Search ${searchValue} Manga Online`,
      description: "Generated by create next app",
    };
  }

const SearchPage = async ({
  searchParams,
}: {
  searchParams?: { [key: string]: string | string[] | undefined };
}) => {
  const { sort, q: searchValue } = searchParams as { [key: string]: string };
  const data = await searchManga(searchValue);
  return <div>
    <MangaScreen mangas={data} newName="" type="Search" searchPage={true} query={searchValue} />
  </div>;
};

export default SearchPage;
