export const metadata = {
  title: "MangaReader - Read Manga website",
  description: "Generated by create next app",
  icons: {
    icon: "https://mangareader.to/favicon.ico?v=0.1",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="w-full relative mx-auto my-0 flex justify-center items-center overflow-x-hidden">
      {children}
    </div>
  );
}
