export const metadata = {
  title: "MangaReader - Read Manga website",
  description: "Generated by create next app",
  icons: {
    icon: "https://mangareader.to/favicon.ico?v=0.1",
  },
};

export default function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <body className="w-full relative mx-auto my-0 flex justify-center items-center">
      {children}
    </body>
  );
}
