import Navbar from './components/navbar/Navbar'
import Slider from './components/slider/Slider'
import './globals.css'
import { Inter } from 'next/font/google'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="w-full h-screen bg-[#1f1f1f] relative">
        <Navbar />
        <Slider />
      </body>
    </html>
  )
}
