import React from "react";
import { notFound } from "next/navigation";
import { Metadata } from "next";
import PageContent from "./ContentPage";
import { getMangaById } from "app/data/dataFetching";


export async function generateMetadata({
  params,
}: {
  params: { name: string };
}): Promise<Metadata> {
  let nameArr = params.name.split("-");
  let mangaId = nameArr[nameArr.length - 1];
  const data = await getMangaById(mangaId);

  if (!data) return notFound();

  return {
    title: `${data.manga.name} Manga Online`,
    description: "Generated by create next app",
  };
}

export default async function Page({ params }: { params: { name: string } }) {
  let nameArr = params.name.split("-");
  let mangaId = nameArr[nameArr.length - 1];
  const data = await getMangaById(mangaId);

  return (
    <div className="max-w-[1400px] w-full overflow-hidden bg-[#1f1f1f] max-xl:mt-[-25px] max-xl:z-[999]">
      <PageContent manga={data.manga} />
    </div>
  );
}
