import { Suspense } from "react";
import Loading from "./loading";

export const metadata = {
  title: "Read Action Online Free",
  description: "Generated by create next app",
  icons: {
    icon: "https://mangareader.to/favicon.ico?v=0.1",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>{children}</>
  );
}
